# Generated by Django 4.2.6 on 2023-10-29 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
